#!/usr/bin/ruby
# coding: utf-8
#
# Scrapbox上にリストしたなぞなぞ問題から10問ランダムに選択
#
# % episoq masui 県名なぞなぞ 3
# 右足を怪我したのは?
# 自転車安く借りて学会行ったのは?
# 魚がステーキみたいだったのは?
# %
#

require 'net/https'
require 'uri'
require 'json'

project = ARGV[0] || 'masui'
page = ARGV[1] || '県名なぞなぞ'
n = ARGV[2] || 10
js = ARGV[3] || 'episopass.js'

api = "https://scrapbox.io/api/code/#{project}/#{URI.encode(page)}/#{js}"
uri = URI.parse(api)
res = Net::HTTP.get_response(uri)

eval "$" + res.body

url = "http://EpisoPass.com/easy.html?" +
      "questions=#{$qa[:questions].shuffle[0...n.to_i].join(';')}" + "&" +
      "answers=#{$qa[:answers].join(';')}"

system "open '#{url}'"


